language: node_js
node_js:
- stable
install:
- npm install
script:
- npm test
before_install:
- openssl aes-256-cbc -K $encrypted_5824f45eeeec_key -iv $encrypted_5824f45eeeec_iv -in build_args -out .env -d
