
version: '3'
services:
    mongodb:
        image: mongo:3.6.6
        container_name: db
        ports:
          - "127.0.0.1:27017:27017"
    gateway:
        build:
          context: .
          dockerfile: Dockerfile
        container_name: parser-server
        command: node index.js
        ports:
          - "127.0.0.1:5000:5000"
        environment:
          NODE_ENV: production
          PROCESS_TYPE: parse-server
          PORT: 5000
        volumes:
          - .:/app
          - /app/node_modules

        env_file: .env
