
version: '3'
services:
    mongodb:
      image: mongo:3.6.6
      container_name: db
      networks:
        api_net:
          ipv4_address: 172.21.179.100

    parse-server:
      build:
        context: .
        dockerfile: Dockerfile
      container_name: parser-server
      command: node index.js
      ports:
        - "127.0.0.1:5000:5000"
      networks:
        api_net:
          ipv4_address: 172.21.179.200
      environment:
        NODE_ENV: production
        PROCESS_TYPE: parse-server
        PORT: 5000
      volumes:
        - .:/app
        - /app/node_modules
      env_file: .env
      depends_on:
        - mongodb
       
# Network config
networks:
  api_net:
    driver: bridge
    ipam:
       driver: default
       config:
       - subnet: 172.21.179.0/24
